### ISSUE TITLE
Object literal may only specify known properties

### ISSUE THREAD

**Issue by amritpratya5** [insidesherpa/JPMC-tech-task-3-PY3#65]
Hi, I am facing this issue:

Type error: Type '{ price_abc: number; price_def: number; ratio: number; timestamp: Date; upper_bound: number; lower_bound: number; trigger_alert: number | undefined; }' is not assignable to type 'Row'.
  Object literal may only specify known properties, and 'price_abc' does not exist in type 'Row'.  TS2322

    20 |     const lowerBound = 1 + 0.05;
    21 |     return { 
  > 22 |         price_abc: priceABC,
       |         ^
    23 |         price_def: priceDEF,
    24 |         ratio,
    25 |         timestamp: serverRespond[0].timestamp > serverRespond[1].timestamp ?

I have attached the code screenshot below:

![Screenshot (224)](https://user-images.githubusercontent.com/64955259/91566092-ca657380-e960-11ea-92b1-dab7e52e1b03.png)

I am working on windows and using sublime text for coding 

Please somebody help, how to resolve this error, I have gone through all the links for reference, but that couldn't help

**Comment by anirbandey303** [comment]
Hi, in your interface I can see the variable names as 'stock_abc' and 'stock_def' but while returning you're using variables 'price_abc' and 'price_def'. I was wondering if that is what's creating the issue.

**Comment by amritpratya5** [comment]
> Hi, in your interface I can see the variable names as 'stock_abc' and 'stock_def' but while returning you're using variables 'price_abc' and 'price_def'. I was wondering if that is what's creating the issue.

Hi, @anirbandey303 
I have changed both the variables names to price_abc and price_def, but the issue remains the same.

**Comment by rongxin-liu** [comment]
The problem is caused by a miss-matched return type. We are expecting the return type to be just the `Row` object, not `Row[]`.

So change `static generateRow(serverResponds: ServerRespond[]): Row[] {}` to `static generateRow(serverResponds: ServerRespond[]): Row {}`

If you read the instruction carefully, it does mention this, though the screenshot does not reflect these changes.

**Comment by kevinbui904** [comment]
Wait did that "fix" work for anybody? (static generateRow(serverResponds: ServerRespond[]): Row{})

because if doesn't really make sense. In this instance we're appending an array type to an object type??? 
![Screenshot 2020-11-09 181415](https://user-images.githubusercontent.com/56280194/98619139-78719000-22b7-11eb-83d2-cddbdeff39dc.png)
